### ISSUE TITLE
no passive steps/workout recorded

### ISSUE THREAD

**Issue by nikhilk90** [Share-Impact/Android-Impact-Issues#107]
https://ced.impactrun.com/userdetail/523322

user is complaining that passive steps were not recorded on 15th June.
Also as per CED there is also an issue of duplicate workouts.

![Screenshot_2020-06-16-16-55-05-90_c24bb60af26cb8edb45f3dfeea801e6a](https://user-images.githubusercontent.com/8169016/84769994-6f281400-aff4-11ea-8cfd-f2d66585ae0d.jpg)

**Comment by sagrgpt** [comment]
User [812454](https://ced.impactrun.com/userdetail/812454) is facing similar issue. 
<p>
<img width="100" height="200" src="https://user-images.githubusercontent.com/11998999/90370284-d01ea780-e08a-11ea-9a1a-9ca367a94eee.jpg">
<img width="100" height="200" src="https://user-images.githubusercontent.com/11998999/90370305-d7de4c00-e08a-11ea-9be0-d5ded2d7d21c.png">
<img width="100" height="200" src="https://user-images.githubusercontent.com/11998999/90370444-0a884480-e08b-11ea-92dd-01000a28e4fa.png">
<img width="100" height="200" src="https://user-images.githubusercontent.com/11998999/90370553-34416b80-e08b-11ea-8eb1-0c8eed086469.png">
<img width="100" height="200" src="https://user-images.githubusercontent.com/11998999/90370921-ccd7eb80-e08b-11ea-8903-aa441cf00d64.png">
<img width="100" height="200" src="https://user-images.githubusercontent.com/11998999/90371032-f98c0300-e08b-11ea-97ac-fe4f73beaead.png">
<img width="100" height="200" src="https://user-images.githubusercontent.com/11998999/90371159-28a27480-e08c-11ea-9373-38a9b26b526d.jpg">
<img width="100" height="200" src="https://user-images.githubusercontent.com/11998999/90371187-30faaf80-e08c-11ea-92b3-2ddd30aec0b6.png">
</p>

**Comment by sagrgpt** [comment]
@nikhilk90 The reported issue for [523322](https://ced.impactrun.com/userdetail/523322) is due to the duplicate indoor workout created. We have worked on this issue recently and since then there wasn't any duplicates reported. Hence, it save to assume that this issue is resolved. 

For [812454](https://ced.impactrun.com/userdetail/812454) the issue occurred because impact steps were more than google fit steps and inserting steps to google fit wasn't successful. I'm creating another issue for this and updates regarding the same will continue there.
