### ISSUE TITLE
[BUG] Discrepancy in my profile and global leaderboard total amount

### ISSUE THREAD

**Issue by sagrgpt** [Share-Impact/Android-Impact-Issues#116]
**Describe the bug**
The total amount displayed in the profile screen is different from that displayed in the all-time global leaderboard. 

**To Reproduce**
1. Go to profile check amount
2. Go to global leader board
3. Check amount

**Expected behavior**
Profile amount and global leaderboard all-time amount should be the same.

**Screenshots**
![WhatsApp Image 2020-06-24 at 11 55 00 AM (1)](https://user-images.githubusercontent.com/11998999/85689537-586a7700-b6f0-11ea-9510-0c452b210a09.jpeg)
![WhatsApp Image 2020-06-24 at 11 55 00 AM](https://user-images.githubusercontent.com/11998999/85689684-7932cc80-b6f0-11ea-92fa-f094e1b42bc4.jpeg)

**Version [Check app's setting screen]:** 2.16.4

**Additional context**
@apunuj : I have checked. This is not a backend bug, but an incorrect data sync pattern in android. Leaderboard data is the latest and most updated. Whereas public profile API is probably not being hit appropriately and hence its showing stale data from a previous API call.

**Comment by parthanjaria** [comment]
The issue was there because of few duplicate workouts. And since duplicate workouts are neglected at client end having the same clientID, thus the value in the profile was correct. I searched all workouts of this users and flagged the duplicate workouts. Now the value in profile and leaderboard are same.
