### ISSUE TITLE
Active workout turned into passive [BUG]

### ISSUE THREAD

**Issue by nikhilk90** [Share-Impact/Android-Impact-Issues#125]
https://ced.impactrun.com/userdetail/383504
workout on 7th of around 21km did not come up, instead a passive workout was created. 

<img width="1440" alt="Screenshot 2020-07-09 at 12 14 28 AM" src="https://user-images.githubusercontent.com/8169016/86958163-5e913680-c179-11ea-87f2-563cfcc9f9d8.png">

https://impactapp.freshchat.com/a/154002725929316/inbox/3/0/conversation/322614919380240

**Comment by sagrgpt** [comment]
@nikhilk90 The workout is create for 21Km on 6/07/20 instead of 07/07/20. This is because the user started the workout on 6th and continued the same workout on 7th. The workouts are ordered and recognized by their start date. 
I hope this issue is resolved. Please reopen if you have any other concerns.
